### PR TITLE
default to remote login services before standard service in login form

### PR DESCRIPTION
**Pull request by walterrowe**

### CODE REVIEW

**Comment by mark0263** [comment]
Can you provide a screenshot or a description of what actually changes with this PR?

**Comment by walterrowe** [comment]
The default is to show to the 'standard' (internal) login service, then show alternate login methods, in the drop-down menu on the login form.
glfusion-login-service-standard-first

This pull request makes the alternate login services first and show the 'standard' (internal) login service last in the drop-down menu on the login form.
glfusion-login-service-standard-last

If no alternative (oauth, Facebook, etc) login methods are offered, it still defaults to the 'standard' (internal) login method.

**Comment by walterrowe** [comment]
I changed the Site Name to "Local Account" so my staff would understand whether they were authenticating against LDAP (AD) or the glfusion internal database.

**Comment by mark0263** [comment]
Instead of hard coding the change, there is now a new configuration option to specify whether the local / standard auth option is displayed before or after 3rd party modules. b9d29852876929c9a37f6b50e6183b1752b8b6cf

**Comment by walterrowe** [comment]
Perfect! Thanks!

**Pull request closed without merging**
