### PR TITLE
Create CSS/UIkit rating stars

### PR DESCRIPTION
**Pull request by leegarner**

### CODE REVIEW

**Comment by mark0263** [comment]
Question: the JS now references rater2_rpc.php - I've updated to rater_rpc.php, but is is throwing an error on $item_id.  Are there updates needed to rater_rpc.php?

**Comment by leegarner** [comment]
Adding previously-omitted public_html/rater2_rpc.php 
[rater2_rpc.php.txt](https://github.com/glFusion/glfusion/files/7816187/rater2_rpc.php.txt)

**Comment by leegarner** [comment]
You're right, I missed that. I just updated the PR by attaching the file. I
was keeping it separate during testing and planned to rename to
rater_rpc.php but overlooked that, obviously.

**Comment by mark0263** [comment]
It might require a new PR since I've already merged this one.

**Comment by mark0263** [comment]
nevermind - I'll use the attachment.

**Comment by leegarner** [comment]
Yeah, I tried a new PR but it wouldn't merge automatically for some reason, couldn't see why but figured the attachment is the easy way. I'll leave it to you whether to just drop it in or rename & update the template ;)

**Comment by leegarner** [comment]
One minor thing I noticed, the extra line-break after voting could be removed for a little better layout.
```
100c100
<     $message = '<br><span class="thanks">&nbsp;' . $LANG13['thanks_for_vote'] . '</span>';
---
>     $message = '<span class="thanks">&nbsp;' . $LANG13['thanks_for_vote'] . '</span>';
```

**Pull request merged**
