### PR TITLE
Set default ownership and permissions on new topic

### PR DESCRIPTION
**Pull request by leegarner**

### CODE REVIEW

**Comment by mark0263** [comment]
Shouldn't we be using the $_CONF settings for default permissions for topic?

**Comment by leegarner** [comment]
You're right, I completely forgot about those config values. I updated this pr to use them.

**Comment by mark0263** [comment]
Not trying to be too picky - but... Looking at how the defaults were set prior to the topic class - I still think we may be missing a couple of things - previously the owner was set to current user - the group was forced to Topic Admin unless it was not set in which case it would then pull the topic.edit group.  What do you think of this approach (pretty much cut / paste for the old way)...

```
        } else {
            $props['tid']           = '';
            $props['topic']         = '';
            $props['description']   = '';
            $props['sortnum']       = 0;
            $props['limitnews']     = ''; // leave empty!
            $props['is_default']    = 0;
            $props['archive_flag']  = 0;
        	$props['sort_by']       = 0;
        	$props['sort_dir']      = 'DESC';
            $props['owner_id']      = '';
            $props['group_id']      = '';
            $props['imageurl']      = '';

            $assoc_stories_submitted = 0;
            $assoc_blocks = 0;
            $assoc_feeds = 0;

            $tidSortNumber = DB_getItem($_TABLES['topics'],'sortnum','tid="'.DB_escapeString($props['sortnum']).'"');
            $newSortNum = $tidSortNumber;

            $props['sortnum'] = $newSortNum;
            // an empty owner_id signifies this is a new block, set to current user
            // this will also set the default values for group_id as well as the
            // default values for topic permissions

            $props['owner_id'] = $_USER['uid'];
            // this is the one instance where we default the group
            // most topics should belong to the Topic Admin group
            if (isset ($_GROUPS['Topic Admin'])) {
                $props['group_id'] = $_GROUPS['Topic Admin'];
            } else {
                $props['group_id'] = SEC_getFeatureGroup ('topic.edit');
            }
            SEC_setDefaultPermissions ($props, $_CONF['default_permissions_topic']);
            $this->setVars($props, true);
            $this->isNew = true;
        }
```

**Comment by leegarner** [comment]
This should be better. Unset properties are treated as empty, but better to set them anyway. I had overlooked the CONF var for limitnews so I changed self::$def_limitnews to use that. In Edit() the sortnum is set to the last topic + 10 for new topics so it will sort after the last topic by default.

**Comment by mark0263** [comment]
Excellent - Thank you!

**Pull request merged**
